"""
Build GASTON-native isodepth/SNAI1-ac score alignment files.

This step is downstream of GASTON training. It does not retrain GASTON and does
not overwrite source h5ad files. For each accepted whole-tissue GASTON sample it
aligns:

- GASTON isodepth and selected domain labels
- production SNAI1-ac EnrichMap score already present in adata.obs
- two missing SNAI1-ac EnrichMap variants computed in memory

The output is deliberately per-sample. A cohort-sized external spot table can be
derived later, but it is not the primary method contract.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from scipy.stats import spearmanr


DATA_ROOT = Path(r"D:\HGSOC_Spatial_Atlas")
GASTON_ROOT = DATA_ROOT / "05_analysis_ready" / "GASTON_method_v1"
VISIUM_ROOT = DATA_ROOT / "05_analysis_ready" / "visium"
SIGNATURE_ROOT = DATA_ROOT / "05_analysis_ready" / "Signature"

GASTON_MANIFEST = GASTON_ROOT / "02_gaston" / "gaston_manifest.csv"
DOMAIN_MANIFEST = GASTON_ROOT / "02_gaston" / "domain_selection_manifest.csv"
REVIEW_DECISIONS = GASTON_ROOT / "03_post_training_qc" / "review_decisions_frozen_20260617.csv"
WEIGHTS_PATH = SIGNATURE_ROOT / "snai1_ac_weights.json"

DEFAULT_OUT_DIR = GASTON_ROOT / "04_isodepth_score_alignment"

PRODUCTION_SCORE_COL = "SNAI1-ac_score"
VARIANTS = [
    {
        "variant_id": "snai1ac_em_smooth_corrected",
        "output_col": "snai1ac_em_smooth_corrected",
        "source": "existing_adata_obs",
        "source_col": PRODUCTION_SCORE_COL,
        "smoothing": True,
        "correct_spatial_covariates": True,
        "description": (
            "Existing production SNAI1-ac EnrichMap score from adata.obs; "
            "generated by the established scoring pipeline with smoothing=True "
            "and correct_spatial_covariates=True."
        ),
    },
    {
        "variant_id": "snai1ac_em_unsmoothed_corrected",
        "output_col": "snai1ac_em_unsmoothed_corrected",
        "score_key": "GASTON_SNAI1ac_unsmoothed_corrected",
        "source": "computed_in_memory",
        "smoothing": False,
        "correct_spatial_covariates": True,
        "description": (
            "Weighted EnrichMap score using snai1_ac_weights.json, "
            "smoothing=False, correct_spatial_covariates=True."
        ),
    },
    {
        "variant_id": "snai1ac_em_unsmoothed_uncorrected",
        "output_col": "snai1ac_em_unsmoothed_uncorrected",
        "score_key": "GASTON_SNAI1ac_unsmoothed_uncorrected",
        "source": "computed_in_memory",
        "smoothing": False,
        "correct_spatial_covariates": False,
        "description": (
            "Weighted EnrichMap score using snai1_ac_weights.json, "
            "smoothing=False, correct_spatial_covariates=False."
        ),
    },
]

OBS_METADATA_COLS = [
    "array_row",
    "array_col",
    "total_counts",
    "n_genes_by_counts",
    "n_genes",
    "n_counts",
    "pct_counts_mt",
    "Malignant",
    "interface_label",
    "interface",
    "LISA_category",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build GASTON isodepth/SNAI1-ac score alignment outputs."
    )
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--samples", nargs="*", default=None)
    parser.add_argument("--manifest", type=Path, default=GASTON_MANIFEST)
    parser.add_argument("--domain-manifest", type=Path, default=DOMAIN_MANIFEST)
    parser.add_argument("--review-decisions", type=Path, default=REVIEW_DECISIONS)
    parser.add_argument("--weights", type=Path, default=WEIGHTS_PATH)
    parser.add_argument("--strict", action="store_true", help="Fail on first sample error.")
    return parser.parse_args()


def require_imports():
    try:
        import anndata as ad  # noqa: F401
        import enrichmap as em  # noqa: F401
    except Exception as exc:
        raise RuntimeError(
            "This script requires anndata and enrichmap. Run it in enrichmap_env."
        ) from exc


def file_sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def read_json(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)
        handle.write("\n")


def safe_float(value: Any) -> float:
    try:
        if value is None or value == "":
            return float("nan")
        return float(value)
    except Exception:
        return float("nan")


def safe_int(value: Any) -> int | None:
    try:
        if value is None or value == "":
            return None
        return int(float(value))
    except Exception:
        return None


def clean_str(value: Any) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except Exception:
        pass
    return str(value)


def safe_spearman(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    mask = np.isfinite(x) & np.isfinite(y)
    if mask.sum() < 3:
        return float("nan")
    if np.nanstd(x[mask]) == 0 or np.nanstd(y[mask]) == 0:
        return float("nan")
    return float(spearmanr(x[mask], y[mask]).statistic)


def stem_for(row: pd.Series) -> str:
    return "__".join(
        [
            str(row["dataset"]),
            str(row["sample"]),
            str(row["layer"]),
            str(row["feature_method"]),
        ]
    )


def h5ad_path(dataset: str, sample: str) -> Path:
    return VISIUM_ROOT / dataset / sample / f"{sample}.h5ad"


def load_inputs(args: argparse.Namespace) -> tuple[pd.DataFrame, dict[str, dict[str, Any]], dict[str, dict[str, Any]]]:
    if not args.manifest.exists():
        raise FileNotFoundError(args.manifest)
    if not args.domain_manifest.exists():
        raise FileNotFoundError(args.domain_manifest)
    if not args.review_decisions.exists():
        raise FileNotFoundError(args.review_decisions)
    if not args.weights.exists():
        raise FileNotFoundError(args.weights)

    manifest = pd.read_csv(args.manifest)
    manifest = manifest[manifest["status"].astype(str).str.lower() == "ok"].copy()
    manifest = manifest[manifest["layer"].astype(str) == "whole"].copy()
    if args.samples:
        manifest = manifest[manifest["sample"].isin(args.samples)].copy()

    domain = pd.read_csv(args.domain_manifest)
    domain_map = {
        (str(r.dataset), str(r.sample), str(r.layer), str(r.feature_method)): r._asdict()
        for r in domain.itertuples(index=False)
    }

    review = pd.read_csv(args.review_decisions)
    review_map = {
        (str(r.dataset), str(r.sample), str(r.layer), str(r.feature_method)): r._asdict()
        for r in review.itertuples(index=False)
    }
    return manifest, domain_map, review_map


def get_present_weights(adata, weights: dict[str, float]) -> dict[str, float]:
    var_names = set(map(str, adata.var_names))
    return {str(g): float(w) for g, w in weights.items() if str(g) in var_names}


def compute_score_variants(adata, weights: dict[str, float]) -> tuple[dict[str, np.ndarray], list[dict[str, Any]]]:
    import enrichmap as em

    values: dict[str, np.ndarray] = {}
    status_rows: list[dict[str, Any]] = []
    present_weights = get_present_weights(adata, weights)
    if not present_weights:
        raise RuntimeError("No SNAI1-ac signature genes present in AnnData var_names.")

    for spec in VARIANTS:
        output_col = spec["output_col"]
        if spec["source"] == "existing_adata_obs":
            source_col = spec["source_col"]
            if source_col not in adata.obs:
                raise RuntimeError(f"Missing existing production score column: {source_col}")
            scores = pd.to_numeric(adata.obs[source_col], errors="coerce").to_numpy(dtype=float)
        else:
            score_key = spec["score_key"]
            score_col = f"{score_key}_score"
            if score_col in adata.obs:
                del adata.obs[score_col]
            em.tl.score(
                adata=adata,
                gene_set=list(present_weights.keys()),
                gene_weights={score_key: present_weights},
                score_key=score_key,
                smoothing=bool(spec["smoothing"]),
                correct_spatial_covariates=bool(spec["correct_spatial_covariates"]),
                batch_key=None,
            )
            if score_col not in adata.obs:
                raise RuntimeError(f"EnrichMap did not create expected score column: {score_col}")
            scores = pd.to_numeric(adata.obs[score_col], errors="coerce").to_numpy(dtype=float)
            del adata.obs[score_col]

        values[output_col] = scores
        finite = np.isfinite(scores)
        status_rows.append(
            {
                "variant_id": spec["variant_id"],
                "output_col": output_col,
                "source": spec["source"],
                "smoothing": spec["smoothing"],
                "correct_spatial_covariates": spec["correct_spatial_covariates"],
                "n_signature_genes": len(weights),
                "n_genes_present": len(present_weights),
                "n_spots": int(len(scores)),
                "n_finite": int(finite.sum()),
                "score_min": float(np.nanmin(scores)) if finite.any() else np.nan,
                "score_max": float(np.nanmax(scores)) if finite.any() else np.nan,
                "score_mean": float(np.nanmean(scores)) if finite.any() else np.nan,
                "score_sd": float(np.nanstd(scores)) if finite.any() else np.nan,
            }
        )

    return values, status_rows


def production_metadata_summary(adata, weights: dict[str, float]) -> dict[str, Any]:
    genes_key = "SNAI1_ac_signature_genes"
    weights_key = "SNAI1_ac_signature_weights"
    expected_genes = set(map(str, weights.keys()))

    genes_present = genes_key in adata.uns
    weights_present = weights_key in adata.uns
    genes_match = False
    weights_match = False
    n_genes_metadata = np.nan

    if genes_present:
        metadata_genes = set(map(str, list(adata.uns[genes_key])))
        n_genes_metadata = len(metadata_genes)
        genes_match = metadata_genes == expected_genes

    if weights_present:
        try:
            metadata_weights = {
                str(g): float(w) for g, w in dict(adata.uns[weights_key]).items()
            }
            weights_match = (
                set(metadata_weights) == expected_genes
                and all(
                    abs(metadata_weights[g] - float(weights[g])) < 1e-9
                    for g in metadata_weights
                )
            )
        except Exception:
            weights_match = False

    return {
        "production_score_col_present": PRODUCTION_SCORE_COL in adata.obs,
        "production_signature_genes_metadata_present": genes_present,
        "production_signature_weights_metadata_present": weights_present,
        "production_signature_metadata_n_genes": n_genes_metadata,
        "production_signature_genes_match_weights_file": genes_match,
        "production_signature_weights_match_weights_file": weights_match,
    }


def load_domain_arrays(row: pd.Series, domain_row: dict[str, Any] | None) -> dict[str, np.ndarray]:
    result_npz = Path(str(row["result_npz"]))
    if not result_npz.exists():
        raise FileNotFoundError(result_npz)

    selected_npz = None
    if domain_row and str(domain_row.get("primary_domain_npz", "")):
        selected_npz = Path(str(domain_row["primary_domain_npz"]))

    source = selected_npz if selected_npz and selected_npz.exists() else result_npz
    z = np.load(source, allow_pickle=True)
    result = np.load(result_npz, allow_pickle=True)

    labels_key = "labels" if "labels" in z.files else "labels_auto"
    arrays = {
        "domain_labels_selected": np.asarray(z[labels_key], dtype=int),
        "isodepth_raw": np.asarray(z["isodepth_raw"], dtype=float),
        "isodepth_malignant_oriented": np.asarray(
            z["isodepth_malignant_oriented"], dtype=float
        ),
        "mask_indices": np.asarray(z["mask_indices"], dtype=int),
        "auto_k": np.asarray(result["auto_k"], dtype=int),
        "domain_array_source": np.array(str(source)),
    }
    return arrays


def build_spot_frame(
    adata,
    row: pd.Series,
    arrays: dict[str, np.ndarray],
    scores: dict[str, np.ndarray],
    domain_row: dict[str, Any] | None,
    review_row: dict[str, Any] | None,
) -> pd.DataFrame:
    mask_indices = arrays["mask_indices"]
    obs = adata.obs.iloc[mask_indices].copy()

    frame = pd.DataFrame(
        {
            "dataset": str(row["dataset"]),
            "sample": str(row["sample"]),
            "layer": str(row["layer"]),
            "feature_method": str(row["feature_method"]),
            "analysis_tier": str(row["analysis_tier"]),
            "include_in_primary_cross_sample": str(row["include_in_primary_cross_sample"]),
            "spot_id": obs.index.astype(str),
            "mask_index": mask_indices,
            "gaston_isodepth_raw": arrays["isodepth_raw"],
            "gaston_isodepth_malignant_oriented": arrays["isodepth_malignant_oriented"],
            "gaston_domain_selected": arrays["domain_labels_selected"],
            "gaston_auto_k": int(arrays["auto_k"][0]),
            "gaston_selected_k": safe_int(domain_row.get("selected_k")) if domain_row else np.nan,
        }
    )

    if "spatial" in adata.obsm:
        spatial = np.asarray(adata.obsm["spatial"])[mask_indices]
        if spatial.ndim == 2 and spatial.shape[1] >= 2:
            frame["spatial_x"] = spatial[:, 0]
            frame["spatial_y"] = spatial[:, 1]

    for col in OBS_METADATA_COLS:
        if col in obs.columns:
            frame[col] = obs[col].to_numpy()

    for output_col, values in scores.items():
        frame[output_col] = values[mask_indices]

    if review_row:
        frame["review_decision"] = clean_str(review_row.get("review_decision", ""))
        frame["review_role"] = clean_str(review_row.get("review_role", ""))

    return frame


def write_sample_outputs(
    out_dir: Path,
    row: pd.Series,
    frame: pd.DataFrame,
    arrays: dict[str, np.ndarray],
) -> tuple[Path, Path]:
    stem = stem_for(row)
    arrays_dir = out_dir / "arrays"
    tables_dir = out_dir / "tables"
    arrays_dir.mkdir(parents=True, exist_ok=True)
    tables_dir.mkdir(parents=True, exist_ok=True)

    table_path = tables_dir / f"{stem}__spot_alignment.csv.gz"
    array_path = arrays_dir / f"{stem}__alignment.npz"

    frame.to_csv(table_path, index=False, compression="gzip")

    npz_payload = {
        "spot_id": frame["spot_id"].astype(str).to_numpy(),
        "mask_indices": frame["mask_index"].to_numpy(dtype=int),
        "isodepth_raw": frame["gaston_isodepth_raw"].to_numpy(dtype=float),
        "isodepth_malignant_oriented": frame[
            "gaston_isodepth_malignant_oriented"
        ].to_numpy(dtype=float),
        "domain_selected": frame["gaston_domain_selected"].to_numpy(dtype=int),
    }
    for col in [v["output_col"] for v in VARIANTS]:
        npz_payload[col] = frame[col].to_numpy(dtype=float)
    if "spatial_x" in frame and "spatial_y" in frame:
        npz_payload["spatial"] = frame[["spatial_x", "spatial_y"]].to_numpy(dtype=float)
    for col in ["array_row", "array_col", "total_counts", "n_genes_by_counts", "Malignant"]:
        if col in frame:
            npz_payload[col] = pd.to_numeric(frame[col], errors="coerce").to_numpy()
    npz_payload["domain_array_source"] = arrays["domain_array_source"]
    np.savez_compressed(array_path, **npz_payload)
    return table_path, array_path


def summarize_sample(
    row: pd.Series,
    frame: pd.DataFrame,
    table_path: Path,
    array_path: Path,
    domain_row: dict[str, Any] | None,
    review_row: dict[str, Any] | None,
    h5ad: Path,
    production_meta: dict[str, Any],
) -> dict[str, Any]:
    smooth = frame["snai1ac_em_smooth_corrected"].to_numpy(dtype=float)
    unsmoothed_corrected = frame["snai1ac_em_unsmoothed_corrected"].to_numpy(dtype=float)
    unsmoothed_uncorrected = frame["snai1ac_em_unsmoothed_uncorrected"].to_numpy(dtype=float)
    isodepth = frame["gaston_isodepth_malignant_oriented"].to_numpy(dtype=float)

    return {
        "dataset": str(row["dataset"]),
        "sample": str(row["sample"]),
        "layer": str(row["layer"]),
        "feature_method": str(row["feature_method"]),
        "analysis_tier": str(row["analysis_tier"]),
        "include_in_primary_cross_sample": str(row["include_in_primary_cross_sample"]),
        "n_spots": int(len(frame)),
        "auto_k": int(frame["gaston_auto_k"].iloc[0]),
        "selected_k": safe_int(frame["gaston_selected_k"].iloc[0]),
        "selection_source": clean_str(domain_row.get("selection_source", "")) if domain_row else "",
        "review_decision": clean_str(review_row.get("review_decision", "")) if review_row else "",
        "review_role": clean_str(review_row.get("review_role", "")) if review_row else "",
        "attention_flags": clean_str(review_row.get("attention_flags", "")) if review_row else "",
        "warning_flags": clean_str(review_row.get("warning_flags", "")) if review_row else "",
        **production_meta,
        "isodepth_vs_smooth_corrected_spearman": safe_spearman(isodepth, smooth),
        "isodepth_vs_unsmoothed_corrected_spearman": safe_spearman(
            isodepth, unsmoothed_corrected
        ),
        "isodepth_vs_unsmoothed_uncorrected_spearman": safe_spearman(
            isodepth, unsmoothed_uncorrected
        ),
        "smooth_vs_unsmoothed_corrected_spearman": safe_spearman(
            smooth, unsmoothed_corrected
        ),
        "smooth_vs_unsmoothed_uncorrected_spearman": safe_spearman(
            smooth, unsmoothed_uncorrected
        ),
        "unsmoothed_corrected_vs_uncorrected_spearman": safe_spearman(
            unsmoothed_corrected, unsmoothed_uncorrected
        ),
        "h5ad_path": str(h5ad),
        "result_npz": str(row["result_npz"]),
        "primary_domain_npz": clean_str(domain_row.get("primary_domain_npz", "")) if domain_row else "",
        "alignment_table": str(table_path),
        "alignment_npz": str(array_path),
    }


def write_readme(out_dir: Path) -> None:
    text = f"""# GASTON Isodepth / SNAI1-ac Score Alignment

Generated by `gaston_build_isodepth_score_alignment.py`.

This folder is downstream of the frozen GASTON run in:

`{GASTON_ROOT}`

It does not retrain GASTON and does not overwrite source h5ad files.

## Score variants

- `snai1ac_em_smooth_corrected`: existing production `SNAI1-ac_score` from the analysis-ready h5ad files. This is the established EnrichMap score with smoothing and spatial covariate correction.
- `snai1ac_em_unsmoothed_corrected`: recomputed weighted EnrichMap score with `smoothing=False`, `correct_spatial_covariates=True`.
- `snai1ac_em_unsmoothed_uncorrected`: recomputed weighted EnrichMap score with `smoothing=False`, `correct_spatial_covariates=False`.

The intentionally rejected fourth option, smoothed without spatial covariate correction, is not generated.

## Outputs

- `arrays/*__alignment.npz`: method-native per-sample arrays for downstream analysis.
- `tables/*__spot_alignment.csv.gz`: compact per-sample spot alignment for inspection.
- `sample_alignment_manifest.csv`: one row per accepted GASTON sample.
- `score_variant_status.csv`: one row per sample and score variant.
- `score_variant_provenance.json`: input files, hashes, and variant definitions.

These files are per-sample by design. They are not a committed cohort-level external spot table.
"""
    (out_dir / "README.md").write_text(text, encoding="utf-8")


def main() -> None:
    args = parse_args()
    require_imports()

    import anndata as ad

    out_dir = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest, domain_map, review_map = load_inputs(args)
    weights = {str(g): float(w) for g, w in read_json(args.weights).items()}

    manifest_rows: list[dict[str, Any]] = []
    status_rows: list[dict[str, Any]] = []
    failures: list[dict[str, str]] = []

    for row in manifest.itertuples(index=False):
        row_s = pd.Series(row._asdict())
        key = (
            str(row_s["dataset"]),
            str(row_s["sample"]),
            str(row_s["layer"]),
            str(row_s["feature_method"]),
        )
        h5ad = h5ad_path(str(row_s["dataset"]), str(row_s["sample"]))
        try:
            if not h5ad.exists():
                raise FileNotFoundError(h5ad)
            domain_row = domain_map.get(key)
            review_row = review_map.get(key)
            arrays = load_domain_arrays(row_s, domain_row)

            adata = ad.read_h5ad(h5ad)
            production_meta = production_metadata_summary(adata, weights)
            scores, sample_status = compute_score_variants(adata, weights)
            frame = build_spot_frame(adata, row_s, arrays, scores, domain_row, review_row)
            table_path, array_path = write_sample_outputs(out_dir, row_s, frame, arrays)
            manifest_rows.append(
                summarize_sample(
                    row_s,
                    frame,
                    table_path,
                    array_path,
                    domain_row,
                    review_row,
                    h5ad,
                    production_meta,
                )
            )
            for status in sample_status:
                status.update(
                    {
                        "dataset": str(row_s["dataset"]),
                        "sample": str(row_s["sample"]),
                        "layer": str(row_s["layer"]),
                        "feature_method": str(row_s["feature_method"]),
                    }
                )
                status_rows.append(status)
            print(f"ok: {row_s['dataset']} / {row_s['sample']} / {row_s['feature_method']}")
        except Exception as exc:
            failure = {
                "dataset": str(row_s.get("dataset", "")),
                "sample": str(row_s.get("sample", "")),
                "feature_method": str(row_s.get("feature_method", "")),
                "error": repr(exc),
            }
            failures.append(failure)
            print(f"ERROR: {failure}")
            if args.strict:
                raise

    pd.DataFrame(manifest_rows).to_csv(out_dir / "sample_alignment_manifest.csv", index=False)
    pd.DataFrame(status_rows).to_csv(out_dir / "score_variant_status.csv", index=False)
    pd.DataFrame(failures).to_csv(out_dir / "failures.csv", index=False)

    write_json(out_dir / "sample_alignment_manifest.json", manifest_rows)
    write_json(out_dir / "score_variant_status.json", status_rows)
    write_json(out_dir / "failures.json", failures)
    write_json(
        out_dir / "score_variant_provenance.json",
        {
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "script": str(Path(__file__).resolve()),
            "gaston_root": str(GASTON_ROOT),
            "manifest": str(args.manifest),
            "domain_manifest": str(args.domain_manifest),
            "review_decisions": str(args.review_decisions),
            "weights_path": str(args.weights),
            "weights_sha256": file_sha256(args.weights),
            "n_signature_genes": len(weights),
            "variants": VARIANTS,
            "notes": [
                "Outputs are derived and per-sample; source h5ad files are not modified.",
                "The smoothed-uncorrected score variant is intentionally not generated.",
            ],
        },
    )
    write_readme(out_dir)

    if failures:
        raise SystemExit(f"Completed with {len(failures)} failure(s). See failures.csv")
    print(f"Done. Wrote {len(manifest_rows)} sample alignments to {out_dir}")


if __name__ == "__main__":
    main()
